# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

# Disable the package module, hiding it from the prompt completely
[aws]
disabled = true

[line_break]
disabled = false

[directory]
truncation_length = 3
read_only = " "

[git_branch]
symbol = " "

[git_commit]
commit_hash_length = 7
format = "on [$hash]($style) "
tag_symbol = "? "

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[? PICKING](bold red)"

[git_metrics]
disabled = false
added_style = 'bold green'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[hg_branch]
symbol = " "

[nodejs]
format = "via [NodeJS $version](bold green) "

[rust]
format = "via [Rust $version](red bold)"
symbol = "? "

[golang]
format = "via [ $version](blue bold)"

[php]
format = "via [PHP $version](147 bold) "

[lua]
format = "via [Lua $version](bold blue) "
