[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.glyph_offset]
y = 9

[font.normal]
family = "JetBrainsMono NFM"

[font.offset]
x = 0
y = 10

[window]
decorations = "buttonless"
dynamic_title = true
opacity = 1.0
title = "Alacritty"

[window.padding]
x = 5
y = 5
