import = ["~/.config/alacritty/themes/themes/kanagawa_wave.toml"]
[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.glyph_offset]
y = 5

[font.normal]
family = "JetBrainsMono NFM"
# family = "GoMono Nerd Font Mono"
# family = "GeistMono Nerd Font"

[font.offset]
x = 0
y = 8

[window]
decorations = "buttonless"
dynamic_title = true
opacity = 1.0
title = "Alacritty"

[window.padding]
x = 5
y = 5
