[general]
# import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]
# import = ["~/.config/alacritty/themes/themes/kanagawa_wave.toml"]
import = ["~/.config/alacritty/themes/themes/gruvbox_dark_hard.toml"]
# import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]
# import = ["~/.config/alacritty/themes/themes/carbonfox.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.glyph_offset]
y = 2

[font.normal]
# family = "IosevkaTerm Nerd Font"
family = "JetbrainsMono Nerd Font"
style = "Regular"
# family = "Terminess Nerd Font"
# family = "SpaceMono Nerd Font"
# family = "GoMono Nerd Font"
# family = "GeistMono Nerd Font"
# family = "FiraCode Nerd Font"
# family = "Hack Nerd Font"

[font.offset]
x = 0
y = 2

[window]
decorations = "buttonless"
dynamic_title = true
# opacity = 1.0
# title = "Alacritty"
startup_mode = "Maximized"

[window.padding]
x = 4
y = 4
